server: 
  port: 9001
spring: 
  datasource: 
    driver-class-name: org.postgresql.Driver
    password: s3cret
    url: jdbc:postgresql://localhost:5432/alfred?serverTimeZone=UTC
    username: docker
    flyway:
      enabled: true
      locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  session:
    store-type: jdbc
    timeout:
      seconds: 50000  
    jdbc:
      initialize-schema: always
  flyway:
    schemas: spring_session
    baseline-on-migrate: true
base64JWTSecretkey: springsession